language: java
install: true
before_install:
  - chmod +x gradlew
  - sudo apt-get -y install at-spi2-core

jdk:
  - openjdk15

git:
  depth: false
  
addons:
  sonarcloud:
    organization: "gurkenlabs-github"

services:
  - xvfb

script:
  - ./gradlew fullbuild --warning-mode all
  - if [[ $TRAVIS_PULL_REQUEST = 'false' && $TRAVIS_REPO_SLUG = "gurkenlabs/litiengine" ]]; then
    sonar-scanner;
    elif true; then
    echo skipping sonar-scanner;
    fi

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle/caches/'
    - '$HOME/.gradle/wrapper/'
