name: Build

on:
  push:
    paths:
      - "**.gradle"
      - "**.kts"
      - "**.properties"
      - "**.java"
      - "**.xml"
      - ".github/workflows/*.yml"
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  fullbuild:
    runs-on: ubuntu-latest

    name: Java 17 build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: JDK 17 Setup
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: SonarCloud Caching
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: D-BUS AT-SPI Installation
        run: sudo apt-get -y install at-spi2-core

      - name: Gradle Permission Fixing
        run: chmod +x gradlew

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            -PskipSpotless

      - name: Package Creation
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jpackage

      - name: Static Analysis
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        if: ${{!github.event.pull_request.head.repo.fork}}
        with:
          arguments: |
            sonarqube
            -PskipSpotless

      - name: Code Style Validation
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck
