name: Build

on:
  push:
    paths:
      - "**.gradle"
      - "**.properties"
      - "**.java"
      - "**.toml"
      - "**.xml"
      - ".github/workflows/*.yml"
    branches:
      - "**"
  pull_request:
    branches:
      - master
jobs:
  fullbuild:
    runs-on: ubuntu-latest

    name: Java 20 build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - name: JDK Setup
        uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: D-BUS AT-SPI Installation
        run: sudo apt-get -y install at-spi2-core

      - name: Build
        run: ./gradlew build -x test -PskipSpotless

      - name: Test
        uses: coactions/setup-xvfb@v1.0.1
        with:
          run: ./gradlew jacocoTestReport -PskipSpotless

      - name: Package Creation
        run: ./gradlew jpackage

      - name: Static Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        if: ${{!github.event.pull_request.head.repo.fork}}
        run: ./gradlew sonar -PskipSpotless

      - name: Code Style Validation
        run: ./gradlew spotlessCheck
