name: Release LITIENGINE

on:
  workflow_dispatch

jobs:
  gradle:
    name: Release build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Prepare release
        env:
          PROPS_RELEASE: "-Prc=1 -Pgh -Prelease=true -PskipJavadoc -PskipSpotless"
          PROPS_GIT: "-PghGitSourceUsername=gurkenlabs -PghGitSourcePassword=\"${{ secrets.GITHUB_TOKEN }}\""
          PROPS_NEXUS: "-PghNexusUsername=${{ secrets.OSSRH_USERNAME }} -PghNexusPassword=${{ secrets.OSSRH_PASSWORD }}"
          PROPS_SIGNING: "-PuseInMemoryKey=true -Psigning.inMemoryKey='${{ secrets.OSSRH_GPG_SECRET_KEY }}' -Psigning.password='${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}'"
        run: ./gradlew prepareVote $(echo $PROPS_RELEASE $PROPS_GIT $PROPS_NEXUS $PROPS_SIGNING) --info -x test
      - name: Publish release
        env:
          PROPS_RELEASE: "-Prc=1 -Pgh -Prelease=true -PskipJavadoc -PskipSpotless"
          PROPS_GIT: "-PghGitSourceUsername=gurkenlabs -PghGitSourcePassword=${{ secrets.GITHUB_TOKEN }}"
          PROPS_NEXUS: "-PghNexusUsername=${{ secrets.OSSRH_USERNAME }} -PghNexusPassword=${{ secrets.OSSRH_PASSWORD }}"
          PROPS_SIGNING: "-PuseInMemoryKey=true -Psigning.inMemoryKey='${{ secrets.OSSRH_GPG_SECRET_KEY }}' -Psigning.password='${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}'"
        run: ./gradlew publishRelease $(echo $PROPS_RELEASE $PROPS_GIT $PROPS_NEXUS $PROPS_SIGNING) --info -x test
