name: Build nightly SNAPSHOT

on:
  workflow_dispatch:
  schedule:
    # Midnight every day
    - cron: "0 0 * * *"
  push:
    # Rerun if workflow changes
    branches:
      - 'master'
    paths:
      - '**/snapshot.yml'

jobs:
  gradle:
    if: github.repository_owner == 'gurkenlabs'
    name: Publish nightly snapshot
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Publish
        env:
          PROPS_RELEASE: "-Prc=1 -Pgh -Prelease=false -PskipJavadoc -PskipSpotless"
          PROPS_GIT: "-PghGitSourceUsername=gurkenlabs -PghGitSourcePassword='${{ secrets.GITHUB_TOKEN }}'"
          PROPS_NEXUS: "-PghNexusUsername='${{ secrets.OSSRH_USERNAME }}' -PghNexusPassword='${{ secrets.OSSRH_PASSWORD }}'"
          PROPS_SIGNING: "-PuseInMemoryKey=true -Psigning.inMemoryKey='${{ secrets.OSSRH_GPG_SECRET_KEY }}' -Psigning.password='${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}'"
        run: ./gradlew prepareVote $(echo $PROPS_RELEASE $PROPS_GIT $PROPS_NEXUS $PROPS_SIGNING) --info -x test
